import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import MainBanner from '../components/MainBanner/MainBanner';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Производство товарного бетона и ЖБИ в Твери — СК «Бетогор»</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="hero-section bg-primary">
        <MainBanner />
      </header>
    </div>
  )
}
